Repository quaternionmedia/milestones, pull requests merged in 2022-07, with the labels that each got.

#10 Upgrade to checkout@v3
  .github/workflows/draft-release.yml
Labels: maintenance :wrench:

#12 Find and fix syntax error with prettier
  .github/release.yml
Labels: bug :bug:

#14 Testing a new pull request
  README.md
Labels: documentation :scroll:, good first issue :new_moon_with_face:

#15 Publish action
  .github/action.yml
  .github/workflows/draft-release.yml
Labels: enhancement :heavy_plus_sign:, CD :building_construction:, breaking :broken_heart:

#16 Bug report template
  .github/ISSUE_TEMPLATE/Bug-Report.yml
Labels: documentation :scroll:, enhancement :heavy_plus_sign:, maintenance :wrench:

#18 Better bug steps
  .github/ISSUE_TEMPLATE/Bug-Report.yml
Labels: bug :bug:

#19 Create `Because` / `Done when` issue template :fountain_pen:
  .github/ISSUE_TEMPLATE/Because-Done.yml
Labels: enhancement :heavy_plus_sign:, maintenance :wrench:
